export const PROGRAM_INSIGHT_GENERATION_TIMEOUT_MS = 60_000
export const PROGRAM_INSIGHT_MAX_TOKENS = 900
export const PROGRAM_INSIGHT_MAX_ATTEMPTS = 10
export const PROGRAM_INSIGHT_REASONING_EFFORT = 'low' as const
